### ISSUE TITLE
tracing for mmap, munmap, brk, sbrk functions

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/retrace#140]
From Kirill (@catap) ....
I think that retrace has missed few syscalls related to "memory managment":
* `mmap`
* `munmap`
* `brk`
* `sbrk`

`mmap` use directly from https://github.com/riboseinc/rnp for example, and `sbrk` has used by `malloc` because it is common way how allocator can alloc a new memory — sbrk to extend data segment or `mmap` anonymous file.

**Comment by catap** [comment]
@jjr840430 but it should support `memoryfuzzing` also ;)

And please keep in mind that `memoryfuzzing` should be only for `mmap(MAP_ANONYMOUS)` or `mmap(MAP_ANON)`, and you should setup a correct `errno` because it has historically succeeded for `EINVAL`.

Also, `brk` and `sbrk` return `-1` and should setup `ENOMEM` as `errno` value.

**Comment by jjr840430** [comment]
Thanks, @catap Will do so.

**Comment by jjr840430** [comment]
#
