### ISSUE TITLE
Interleaving output on multi-threaded programs

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/retrace#199]
In multi-threaded programs, retrace produces outputs per thread (at least on STDOUT) that is naturally, interleaving, and therefore very difficult to read.

Perhaps output of these should be controlled by a separate "retrace thread" using a provider-consumer model?

**Comment by riataman** [comment]
I put a mutex so that we should be printing complete lines in multithread programs.

Also printed the thread id (in threads other than the main thread) so that the output could be grepped for a particular thread.

The other thing that I wanted to try is an option to write each thread/process to a different log file.

**Comment by ronaldtse** [comment]
@riataman , any plans now to separate writing each thread / forked process to a different file? Technically we can already do that with shell grepping as each line shows the thread / process ID. But we're missing a ready-made example.
